# Generated by Django 5.2.8 on 2025-11-24 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
            },
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="tasks.task",
            ),
        ),
    ]
